myblog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'index/', views.index),
    url(r'article/(?P<article_id>[0-9]+)', views.article_page, name='article_page'),
    url(r'edit/(?P<article_id>[0-9]+)', views.edit_page, name='edit_page'),
    url(r'action/(?P<article_id>[0-9]+)', views.edit_action, name='edit_action'),
    url(r'delete/(?P<article_id>[0-9]+)', views.delete_action, name='delete_action'),

]

myblog/blog2/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'index/', views.index),
]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^blog2/', include('blog2.urls')),
]

myblog/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Article(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(max_length=32, default='Content')

    def __str__(self):
        return self.title


class Animal(models.Model):
    name = models.CharField(max_length=32, default='...')

    def __str__(self):
        return self.name

myblog/blog2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

myblog/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from blog.models import Article


def index(request):
    articles = Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

def article_page(request, article_id):
    article = Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})

def edit_page(request, article_id=None):
    if article_id == '0':
        return render(request, 'blog/edit_page.html')
    article = Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})

def edit_action(request, article_id=None):
    title = request.POST.get('title')
    content = request.POST.get('content')

    if article_id == "0":
        Article.objects.create(title=title, content=content)
    else:
        article = Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
    articles = Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def delete_action(request, article_id):
    article = Article.objects.get(pk=article_id)
    article.delete()
    articles = Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

myblog/blog2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'blog2/index.html', {'hello': 'hello blog2'})

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article_page</title>
</head>
<body>
<h1>{{ article.title}}</h1>
<br>
<p1>{{ article.content}}</p1>
<br><br>
<a href="{% url 'blog:edit_page' article.id %}">Edit this article</a>
<br>
<br>
<a href="{% url 'blog:delete_action' article.id %}">Delete this article</a>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>"Edit Page"</title>
</head>
<body>
     {% if article %}
        <form action="{% url 'blog:edit_action' article.id %}" method="post">
            {% csrf_token %}
            <label>Title
                <input type="text" name="title" value="{{article.title}}"><br>
            </label>
            <br>
            <label>Content
                <input type="text" name="content" value="{{article.content}}"><br>
            </label>
            <h2><input type="submit" value="Submit"></h2>
        </form>

    {% else %}
        <form action="{% url 'blog:edit_action' 0 %}" method="post">
        {% csrf_token %}
            <label>Title
                <input type="text" name="title"><br>
            </label>
            <br>
            <label>Content
                <input type="text" name="content"><br>
            </label>
            <br>
            <h2><input type="submit" value="Submit"></h2>
        </form>
    {% endif %}

</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">Add a new article</a>
</h1>
<h1>All my articles</h1>
    {% for article in articles %}
        <a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
        <br>
        <br>
    {% endfor %}


</body>
</html>

myblog/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{hello}}</h1>
</body>
</html>